### ISSUE TITLE
Default install instructions fail (cannot find Triton)

### ISSUE THREAD

**Issue by ankrgyl** [ELS-RD/kernl#118] opened 2022-10-26 18:32 UTC
```
$ python3.10 -m venv venv
$ source venv/bin/activate
$ pip install torch -U --extra-index-url https://download.pytorch.org/whl/cu116
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch
  Using cached https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp310-cp310-linux_x86_64.whl (1904.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.12.1+cu116 typing-extensions-4.4.0

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
$ cd ../kernl
$ pip freeze | grep torch
torch==1.12.1+cu116
$ pip install -e .
Obtaining file:///home/ubuntu/layoutlm/kernl
  Preparing metadata (setup.py) ... done
Collecting torchdynamo@ git+https://github.com/pytorch/torchdynamo.git@6bd5b8bb8888d5dab0b9574b20f00de975eebc72
  Using cached torchdynamo-1.13.0.dev0-cp310-cp310-linux_x86_64.whl
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from kernl) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0)
ERROR: No matching distribution found for triton==2.0.0
```

System info:

```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

(running on a Lambda Labs GPU instance)

**Comment by pommedeterresautee** [comment] 2022-10-26 19:25
Thank you for your message.

I have been able to reproduce on Python 3.10
On Python 3.9 there is no such issue.

In Triton README they say:

```
Binary wheels are available for CPython 3.6-3.9 and PyPy 3.6-3.7.
```

We will update the requirements of Kernl to match those versions.
Would it be possible for you to either:
- use the Docker image of this repo
- use Python 3.9
- try to install triton directly from source (this commit: `f55960e773b6d84cf8e5b79464816ffdd0fb81b6`) on Python 3.10 (not tested but no good reason to not work)

**Comment by ankrgyl** [comment] 2022-10-26 19:30
Yep. I installed from source, and later ran into this stack trace:

```
Traceback (most recent call last):
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/qa_loop.py", line 40, in <module>
    qa_pipe(context="The Amazon Rainforest is 100 meters big", question="How big is the Amazon rainforest?")
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/question_answering.py", line 380, in __call__
    return super().__call__(examples[0], **kwargs)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1074, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1096, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 990, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/question_answering.py", line 500, in _forward
    start, end = self.model(**model_inputs)[:2]
  File "/home/ubuntu/layoutlm/kernl/src/kernl/model_optimization.py", line 50, in run
    return original_model.forward2(*args, **kwargs)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/eval_frame.py", line 148, in catch_errors
    return callback(frame, cache_size)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/convert_frame.py", line 347, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/convert_frame.py", line 108, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/convert_frame.py", line 288, in _convert_frame_assert
    code = transform_code_object(frame.f_code, transform)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/convert_frame.py", line 264, in transform
    tracer.run()
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/symbolic_convert.py", line 312, in run
    and self.step()
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/symbolic_convert.py", line 290, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/symbolic_convert.py", line 1335, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/output_graph.py", line 307, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/output_graph.py", line 348, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/torchdynamo/output_graph.py", line 371, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compiler raised AssertionError: input and weight bias must have the same dtype: torch.float32, torch.float16
```

with the following script:

```
from transformers import (
    pipeline,
)
import time
import torch
from kernl.model_optimization import optimize_model

MODEL = "distilbert-base-cased-distilled-squad"
qa_pipe = pipeline("question-answering", device=0, model="distilbert-base-cased-distilled-squad")
qa_pipe.model = optimize_model(qa_pipe.model)

if __name__ == "__main__":
    full_loop = time.time()

    for i in range(100):
        qa_pipe(context="My name is Clara and I live in Berkeley.", question="What's my name?")

    print(time.time() - full_loop)
```

**Comment by pommedeterresautee** [comment] 2022-10-26 19:40
I think it misses a few things:
- autocast : to get fp16 weights, that's the reason of the issue
- warmup, otherwise the measure will include compilation
- synchronization, otherwise the measure may be too optimistic

Sorry to have a bit complexified the script but it should look something like that:

```
from transformers import (
    pipeline,
)
import time
import torch
from kernl.model_optimization import optimize_model

MODEL = "distilbert-base-cased-distilled-squad"
qa_pipe = pipeline("question-answering", device=0, model="distilbert-base-cased-distilled-squad")
qa_pipe.model = optimize_model(qa_pipe.model)

if __name__ == "__main__":

    with torch.cuda.amp.autocast(), torch.inference_mode():
        for i in range(10):
            qa_pipe(context="My name is Clara and I live in Berkeley.", question="What's my name?")
    torch.cuda.synchronize()
    with torch.cuda.amp.autocast(), torch.inference_mode():
        full_loop = time.time()
        for i in range(100):
            qa_pipe(context="My name is Clara and I live in Berkeley.", question="What's my name?")
        torch.cuda.synchronize()
        print(time.time() - full_loop)

```
On my machine it prints `0.13`

**Comment by ankrgyl** [comment] 2022-10-26 19:51
Thank you! The script now runs. I think you accounted for this in your script (with the first 10 iters). The first run is very slow (~37s+) but the loop is VERY fast. Here's what I'm seeing:

```
Outside context
First run
Inside context starting
/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/base.py:1043: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
Inside context 0.1481316089630127
Inside context synchronize 0.14818644523620605
Outside context 35.39087414741516
```

And if I remove the `optimize_model` call:

```
Outside context
First run
Inside context starting
/home/ubuntu/layoutlm/layoutlmv2-experiments/venv/lib/python3.10/site-packages/transformers/pipelines/base.py:1043: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
Inside context 0.4925086498260498
Inside context synchronize 0.49256324768066406
Outside context 1.3482463359832764
```

code:

```
from transformers import (
    pipeline,
)
import time
import torch
from kernl.model_optimization import optimize_model

MODEL = "distilbert-base-cased-distilled-squad"
qa_pipe = pipeline("question-answering", device=0, model="distilbert-base-cased-distilled-squad")
qa_pipe.model = optimize_model(qa_pipe.model)

if __name__ == "__main__":
    print("Outside context")
    outside_context = time.time()
    with torch.cuda.amp.autocast(), torch.inference_mode():
        print("First run")
        qa_pipe(context="My name is Clara and I live in Berkeley.", question="What's my name?")
        print("Inside context starting")
        inside_context = time.time()
        for i in range(100):
            qa_pipe(context="My name is Clara and I live in Berkeley.", question="What's my name?")
        print("Inside context", time.time() - inside_context)
        torch.cuda.synchronize()
        print("Inside context synchronize", time.time() - inside_context)
    print("Outside context", time.time() - outside_context)
```

**Comment by pommedeterresautee** [comment] 2022-10-26 20:35
The very first run compile the kernels and builds the CUDA graphs. Moreover, we know we are using an old endpoint of Triton with lots of CPU overhead, we have an issue to move to a newer one which is expected to make the warmup much much faster (at least it's our hope :-) ).

**Comment by ankrgyl** [comment] 2022-10-26 20:39
Okay awesome, it's clearly still worth the tradeoff!

**Comment by pommedeterresautee** [comment] 2022-10-27 11:06
closing as #123 makes 3.9 mandatory

**Closed by pommedeterresautee** 2022-10-27 11:06 UTC
Labels: bug
